config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'welcome#home'

  resources :songs do 
  	member do
  		get :download

  	end
  	collection do
  		get :play
  	end
  end

  resources :moods

end

app/models/mood.rb
class Mood < ActiveRecord::Base

	has_many :taggings
	has_many :songs, through: :taggings

end

app/models/song.rb
class Song < ActiveRecord::Base

	mount_uploader :song_url, AvatarUploader

	after_destroy :delete_song_folder

	after_destroy :delete_moods

	validates :song_title, presence: true
	validates :song_url, presence: true

	belongs_to :user

	has_many :taggings, dependent: :destroy
	has_many :moods, through: :taggings, dependent: :destroy

	def mood_list
		self.moods.collect do |mood|
			mood.name
		end.join(", ")
	end

	def mood_list=(moods_string)
		mood_names=moods_string.split(",").collect{|s| s.strip.downcase}.uniq
		new_or_found_moods=mood_names.collect{|name| Mood.find_or_create_by(name: name)}
		self.moods=new_or_found_moods
	end

	def delete_moods
		@mood = Mood.all
		@mood.each do |m|
			unless Tagging.exists?(mood_id: m.id)
				m.destroy
			end
		end
	end

	def delete_song_folder			
    	FileUtils.remove_dir(File.join(Rails.root, File.join( 'public', self.song_url.store_dir)), :force => true)  
    end

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :mood
  belongs_to :song
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :songs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController

	def index
		@moods=Mood.all
	end

	def show
		@mood=Mood.find(params[:id])
	end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

	skip_before_filter :authenticate_user!, :only => :play

	def index
		@u=current_user
		@songs=@u.songs.order("LOWER(song_title)")
	end

	def play
		if params[:q].present?
			@songs=Song.where("song_title like ?", "%#{params[:q]}%").order("LOWER(song_title)")
		else
			@songs=Song.all.order("LOWER(song_title)")
		end
	end

	def new
		@song=Song.new
	end

	def create
		@song = current_user.songs.new(song_params)
		@song.song_title = params[:song][:song_url].original_filename if params[:song][:song_url].present?
		if @song.save
			redirect_to songs_path,notice: "The song #{@song.song_title} has been uploaded"
		else
			render "new"
		end
	end

	def download
		@song = Song.find(params[:id])
		 send_file(@song.song_url.path,
          :type => @song.song_url.content_type,
          :disposition => 'attachment',
          :url_based_filename => true)
	end

	def destroy		
		@song=Song.find(params[:id])
		@song.destroy
		redirect_to songs_path, notice: "The song has been deleted"
	end

	private
	def song_params
		params.require(:song).permit(:song_title, :song_url, :mood_list)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	skip_before_filter :authenticate_user!, :only => :home
	
	def home

	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def active_tab tab=nil
		if tab == 'home'
			return "active" if controller_name == "index" && action_name == "show"
		elsif tab == 'your_list'
			return "active" if controller_name == "songs" && action_name == "index"
		elsif tab == 'mood'
			return "active" if controller_name == "moods" && action_name == "index"
		elsif tab == 'play'
			return "active" if controller_name == "songs" && action_name == "play"
		elsif tab == 'upload'
			return "active" if controller_name == "songs" && action_name == "new"
		else
			return ""
		end
	end
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RORPmusic</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
	<body>
		<%= render 'shared/navbar' %>
		<%= yield %>
		<%= render 'shared/foot' %>
	</body>
</html>

app/views/moods/index.html.erb
<header class="jumbotron">
	<h1>Choose your Mood <span class="glyphicon glyphicon-headphones"></span></h1>
</header>
<div class="conatiner">
	<div class="well">
		<ul>
			<% @moods.each do |mood| %>
				<li><%= link_to mood.name, mood_path(mood),class: "btn btn-default" %></li><br>
			<% end %>
		</ul>  
	</div>
</div>

app/views/moods/show.html.erb
<header class="jumbotron">
	<h1>Songs with this Mood <span class="glyphicon glyphicon-play"></span></h1>
</header>
<div class="container">
	<div class="well">
		<table class="table table-striped">
			<thead>
				<th>Song Name</th>
				<th>Play</th>
			</thead>		
			<tbody>
				<% @mood.songs.each do |song| %>
					<tr>
						<td><%= song.song_title %></td>
						<td>
							<audio controls class="audio">
	  							<source src="<%=song.song_url.url %>" type="audio/mpeg">
									Your browser does not support the audio element.
							</audio>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/shared/_foot.html.erb
<footer>
	<h4>Copyright&copy; Reserved 2017</h4>
	<p>Ruby on Rails Project By: <strong>Shubham Soni</strong></p>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" style="margin: 0;">
	<div class="container-fluid">
     <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#my_navbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
       <%= link_to "pmusic",root_path, class: "navbar-brand" %>
     </div>
     <div class="collapse navbar-collapse navbar-right" id="my_navbar">
       <ul class="nav navbar-nav ">
        <li class="<%= active_tab('home') %>"><%= link_to "Home",root_path, class: 'home_path' %></li>
        <li class="<%= active_tab('play') %>"><%= link_to "Play", play_songs_path, class: 'play_path' %></li>
        <li class="<%= active_tab('your_list') %>"><%= link_to "Your List", songs_path, class: 'your_list_path' %></li> 
        <li class="<%= active_tab('mood') %>"><%= link_to "Mood", moods_path, class: 'mood_path' %></li>
        <li class="<%= active_tab('upload') %>"><%= link_to "Upload", new_song_path, class: 'new_path' %></li>
        <form class="navbar-form navbar-left" action="<%= play_songs_path %>">
          <div class="form-group">
            <input type="text" name="q" value="<%= params[:q] %>" class="form-control" placeholder="Search a song">
          </div>
          <button type="submit" class="btn btn-primary">Search</button>
        </form>
        <% if current_user.present? %>
            <li><span class="text-primary" style="line-height: 50px; color: green;"><%= current_user.email %></span></li>
            <li class="navbar-form"><%= link_to "Logout", destroy_user_session_path, method: :delete ,class: "btn btn-danger", style: "color:black;   padding: 6px 12px;" %></li>
          <%else%>
            <li><%= link_to "Login", new_user_session_path,class: "glyphicon glyphicon-log-in" %></li>
            <li><%= link_to "SignUp", new_user_registration_path, class: "glyphicon glyphicon-user" %></li>
        <% end %>
     </ul>
     </div>     
  </div>
</nav>

app/views/songs/index.html.erb
<header class="jumbotron">
	<h1>Songs List <span class="glyphicon glyphicon-th-list"></span></h1>
</header>
<div class="container">
	<% if !flash[:notice].blank? %>
	<div class = "alert alert-info">
		<%= flash[:notice] %>
	</div>
	<% end %>
</div>
<div class="container">
	<%= link_to "Upload New Song" ,new_song_path, class: "btn btn-primary",id: "song_title" %>
	<br><br>

	<div class="well">
		<table class="table table-striped">
			<thead>
				<th>Song Name</th>
				<th>Download Link</th>
				<th>Delete</th>
				<th>Moods</th>
			</thead>		
			<tbody>
				<% @songs.each do |song| %>
				<tr>
					<td><%= song.song_title %></td>
					<td><%= link_to " Download ", download_song_path(song), target: :_blank, class: "btn btn-primary glyphicon glyphicon-download-alt" %></td>
					<td><%= button_to "Delete song", song_path(song), method: :delete, class: "btn btn-danger" ,confirm: "Are you sure that you wish to delete #{song.song_title}?" %></td>
					<td>						 
						<% song.moods.each do |mood| %>
							<%= link_to mood.name, mood_path(mood) %>
						<% end %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
	<br>
	<%= link_to "Play These Songs" ,play_songs_path, class: "btn btn-success",id: "song_play" %>
</div>

app/views/songs/new.html.erb
<header class="jumbotron">
	<h1>Upload Song <span class="glyphicon glyphicon-cloud-upload"></span></h1>
</header>
<div class="container">

	<% if !@song.errors.empty? %>
	   <div class = "alert alert-error">	      
	      <ul>
	         <% @song.errors.full_messages.each do |msg| %>
	            <li><%= msg %></li>
	         <% end %>
	      </ul>	      
	   </div>
	<% end %>

	<div class="well">
		<%= form_for(@song, html: { multipart: true }) do |f| %>
		<p>
			<%= f.label :song_url %><br>
			<%= f.file_field :song_url %>
		</p>
		<p>
			<%= f.label :mood_list %><br>
			<%= f.text_field :mood_list%>
		</p>
		<p>
			<%= f.submit "Upload",class: "btn btn-primary" %>
		</p>
		<% end %>	
	</div>
</div>

app/views/songs/play.html.erb
<header class="jumbotron">
	<h1>Play here <span class="glyphicon glyphicon-play"></span></h1>
</header>
<div class="container">
	<div class="well">
		<table class="table table-striped">
			<thead>
				<th>Song Name</th>
				<th>Play</th>
				<th>Moods</th>
			</thead>		
			<tbody>
				<% @songs.each do |song| %>
					<tr>
						<td><%= song.song_title %></td>
						<td>
							<audio controls class="audio">
	  							<source src="<%=song.song_url.url %>" type="audio/mpeg">
									Your browser does not support the audio element.
							</audio>
						</td>
						<td>						 
							<% song.moods.each do |mood| %>
								<%= link_to mood.name, mood_path(mood) %>
							<% end %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
	<%= link_to "Upload New Song" ,new_song_path, class: "btn btn-primary",id: "song_upload" %>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$('audio').on('play', function(){
    		$("audio").not(this).trigger('pause');
		});
	});
</script>

app/views/welcome/home.html.erb
<div class="jumbotron">
	<h1>pmusic <span class="glyphicon glyphicon-music"></span></h1>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<%= link_to play_songs_path do %>
				<%= image_tag("songs_listen_icon.jpg", class: "thumbnail")%>
			<% end %>			
			<div class="caption">
				<h3>Play</h3>
				<p>We can play our songs here</p>
			</div>  
		</div>
		<div class="col-md-6">
			<%= link_to moods_path do %>	
				<%= image_tag("songs_mood_icon.jpg", class: "thumbnail") %>
			<% end %>
			<div class="caption">
				<h3>Mood</h3>
				<p>Play as of your Mood</p>
			</div>
		</div>
	</div>
	<div class="row">	
		<div class="col-md-6">
			<%= link_to songs_path do %>	
				<%= image_tag("songs_search_icon.jpg", class: "thumbnail") %>
			<% end %>
			<div class="caption">
				<h3>Search</h3>
				<p>We can Search our songs here</p>
			</div>
		</div>
		<div class="col-md-6">
			<%= link_to new_song_path do %>
				<%= image_tag("songs_upload_icon.png", class: "thumbnail") %>
			<% end %>
			<div class="caption">
				<h3>Upload</h3>
				<p>We can Upload our songs here</p>
			</div>
		</div>
	</div>
</div>